# Generated by Django 4.1.3 on 2022-11-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_image', models.ImageField(upload_to='place_images')),
                ('place_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
