# Generated by Django 4.1.3 on 2022-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_image', models.ImageField(upload_to='activity_images')),
                ('place_foreign', models.CharField(max_length=100)),
                ('activity_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
