# Generated by Django 4.0.6 on 2022-11-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField(max_length=300)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_image')),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100)),
                ('guide_image', models.ImageField(blank=True, null=True, upload_to='guide_images')),
                ('guide_description', models.TextField(max_length=200)),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=100)),
                ('festival_desc', models.TextField(max_length=300)),
                ('festival_image', models.ImageField(blank=True, null=True, upload_to='festival_image')),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
    ]
