# Generated by Django 4.1.4 on 2023-02-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='place_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
