# Generated by Django 4.1.4 on 2023-02-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attact_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attraction')),
                ('place_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
                ('user_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
